# Generated by Django 5.0.4 on 2024-07-25 12:53

import anchor.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anchor', '0001_initial'),
        ('base', '0002_post_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cover', anchor.models.fields.BlobField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+')),
                ('customer_records', anchor.models.fields.BlobField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+')),
                ('poster', anchor.models.fields.BlobField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+')),
            ],
        ),
    ]
