# Generated by Django 5.0.4 on 2024-07-25 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='customer_records',
        ),
    ]
