# Generated by Django 5.0.4 on 2024-07-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_movie_customer_records'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='poster',
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_cover',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_posters',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
